apiVersion: v1
kind: ConfigMap
metadata:
  name: xtdb-yaml-config
  namespace: {{ .Release.Namespace }}
data:
  xtdbconfig.yaml: |-
    {{- (.Values.providerConfig.nodeConfig | default dict) | toYaml | nindent 4 }}
