version: "3.6"
services:
  crux-http:
    build:
      context: .
    image: juxt/crux-http
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:7888:7888"
    volumes:
      - "m2:/root/.m2"
      - "crux-dev-data:/var/lib/crux"
      - "./crux.edn:/etc/crux.edn"
      - "./deps.edn:/usr/lib/crux/deps.edn"
      - "./logback.xml:/usr/lib/crux/resources/logback.xml"

volumes:
  m2:
  crux-dev-data:
