apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xtdb-statefulset
  namespace: {{ .Release.Namespace }}
  labels:
    app: xtdb-statefulset
spec:
  serviceName: xtdb-service
  replicas: {{ .Values.nodeCount }}
  selector:
    matchLabels:
      app: xtdb-statefulset
  template:
    metadata:
      labels:
        app: xtdb-statefulset
    spec:
      # Requires the service account to be created & federated identity set up
      serviceAccountName: {{ required (printf "xtdbConfig.serviceAccount is required - ensure you set it up on %s and federate with a Google Cloud IAM service account" .Release.Namespace) .Values.xtdbConfig.serviceAccount }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes: 
        - name: "tmp"
          emptyDir: {}
        - name: xtdb-yaml-config
          configMap:
            name: xtdb-yaml-config
        - name: "local-disk-cache"
          emptyDir:
            sizeLimit: {{ .Values.xtdbConfig.localDiskCache.sizeLimit }}
      containers:
        - name: xtdb-container
          image: {{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ['-f', '/var/lib/xtdb-config/xtdbconfig.yaml']
          volumeMounts:
            - name: "tmp"
              mountPath: "/tmp"
            - mountPath: /var/lib/xtdb-config/xtdbconfig.yaml
              name: xtdb-yaml-config
              subPath: xtdbconfig.yaml
            - name: local-disk-cache
              mountPath: "/var/lib/xtdb/buffers/"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.xtdbConfig.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: JDK_JAVA_OPTIONS
              value: {{ .Values.xtdbConfig.jdkOptions }}
            - name: XTDB_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ required "xtdbConfig.kafkaBootstrapServers is required." .Values.xtdbConfig.kafkaBootstrapServers }}
            - name: KAFKA_LOG_TOPIC
              value: {{ required "xtdbConfig.kafkaLogTopic is required." .Values.xtdbConfig.kafkaLogTopic }}
            - name: GCP_PROJECT_ID
              value: {{ required "xtdbConfig.gcpProjectId is required." .Values.xtdbConfig.gcpProjectId }}
            - name: GCP_BUCKET
              value: {{ required "xtdbConfig.gcpBucket is required." .Values.xtdbConfig.gcpBucket }}
            {{- range $key, $value := .Values.xtdbConfig.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
