apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "xtdb-pvc-local-caches"
  namespace: "cloud-benchmark"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "50Gi"
  storageClassName: "managed-csi"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "xtdb-env-config"
  namespace: "cloud-benchmark"
data:
  CLOUD_PLATFORM_NAME: "Azure"
  XTDB_AZURE_USER_MANAGED_IDENTITY_CLIENT_ID: "c76c6e6a-59e2-4172-8097-6c48d36cdb92"
  XTDB_AZURE_STORAGE_ACCOUNT: "xtdbazurebenchmark"
  XTDB_AZURE_STORAGE_CONTAINER: "xtdbazurebenchmarkcontainer"
  XTDB_AZURE_SERVICE_BUS_NAMESPACE: "cloud-benchmark-eventbus"
  XTDB_AZURE_SERVICE_BUS_TOPIC_NAME: "cloud-benchmark-servicebus-topic"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service.cloud-benchmark.svc.cluster.local:9092"
  XTDB_TOPIC_NAME: "xtdb-topic"
  AUCTIONMARK_DURATION: "PT1H"
  AUCTIONMARK_SCALE_FACTOR: "0.1"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "xtdb-multi-node-auctionmark"
  namespace: "cloud-benchmark"
  labels:
    app: "xtdb-multi-node-auctionmark"
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: "xtdb-multi-node-auctionmark"
        azure.workload.identity/use: "true" 
    spec:
      nodeSelector:
        nodepool: "benchmark"
      serviceAccountName: "xtdb-service-account"
      restartPolicy: "Never"
      volumes:
        - name: "xtdb-pvc-local-caches-vol"
          persistentVolumeClaim:
            claimName: "xtdb-pvc-local-caches"
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command: ['sh', '-c', 'until nc -z kafka-service.cloud-benchmark.svc.cluster.local 9092; do echo waiting for kafka; sleep 5; done;']
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "256Mi"
      - name: load-phase
        image: cloudbenchmarkregistry.azurecr.io/xtdb-azure-bench:latest
        volumeMounts:
        - mountPath: /var/lib/xtdb/buffers
          name: xtdb-pvc-local-caches-vol
        resources:
          requests:
            memory: "5120Mi"
          limits:
            memory: "5120Mi"
        envFrom:
        - configMapRef:
            name: xtdb-env-config
        env:
        - name: XTDB_LOCAL_DISK_CACHE
          value: "/var/lib/xtdb/buffers/disk-cache-lp"
        - name: AUCTIONMARK_LOAD_PHASE_ONLY
          value: "True"
      containers:
      - name: xtdb-azure-bench-1
        image: cloudbenchmarkregistry.azurecr.io/xtdb-azure-bench:latest
        volumeMounts:
        - mountPath: /var/lib/xtdb/buffers
          name: xtdb-pvc-local-caches-vol
        resources:
          requests:
            memory: "5120Mi"
          limits:
            memory: "5120Mi"
        envFrom:
        - configMapRef:
            name: xtdb-env-config
        env:
        - name: XTDB_LOCAL_DISK_CACHE
          value: "/var/lib/xtdb/buffers/disk-cache-1"
        - name: AUCTIONMARK_LOAD_PHASE
          value: "False"
      - name: xtdb-azure-bench-2
        image: cloudbenchmarkregistry.azurecr.io/xtdb-azure-bench:latest
        volumeMounts:
        - mountPath: /var/lib/xtdb/buffers
          name: xtdb-pvc-local-caches-vol
        resources:
          requests:
            memory: "5120Mi"
          limits:
            memory: "5120Mi"
        envFrom:
        - configMapRef:
            name: xtdb-env-config
        env:
        - name: XTDB_LOCAL_DISK_CACHE
          value: "/var/lib/xtdb/buffers/disk-cache-2"
        - name: AUCTIONMARK_LOAD_PHASE
          value: "False"
      - name: xtdb-azure-bench-3
        image: cloudbenchmarkregistry.azurecr.io/xtdb-azure-bench:latest
        volumeMounts:
        - mountPath: /var/lib/xtdb/buffers
          name: xtdb-pvc-local-caches-vol
        resources:
          requests:
            memory: "5120Mi"
          limits:
            memory: "5120Mi"
        envFrom:
        - configMapRef:
            name: xtdb-env-config
        env:
        - name: XTDB_LOCAL_DISK_CACHE
          value: "/var/lib/xtdb/buffers/disk-cache-3"
        - name: AUCTIONMARK_LOAD_PHASE
          value: "False"
