site:
  title: XTDB Core2 Docs
  start_page: main::index.adoc
  url: https://core2docs.xtdb.com
  # homeUrl: &home_url /xyz/5.2/index.html
  keys:
    main_site_url: 'https://xtdb.com/'
    main_site_title: 'XTDB Core2 - Home'
    analytics_url: 'https://bunseki.juxt.pro'
    analytics_site_id: 'c5026354-28df-4f0c-a17d-43d1a01b2c94'
    github_url: 'https://github.com/xtdb/core2'
    typesense_host: 'xtagzc25w84ufq37p-1.a1.typesense.net'
    typesense_api_key: '0zVHpGQFDUhgP9hazp1laLklfy00AlGD'
    typesense_collection_name: 'xtdb-website-ts-index'
    hidden_component: 'main'

content:
  edit_url: 'https://github.com/xtdb/core2/edit/{refname}/{path}'
  sources:
    - url: ../../
      start_path: doc/adoc/main # index - Only necessary to read self-hosted docs.
      branches: master
    - url: ../../
      start_path: doc/adoc/language-reference
      branches:
        - master
    - url: ../../
      start_path: doc/adoc/clients
      branches:
        - master
    - url: ../../
      start_path: doc/adoc/getting-started
      branches:
        - master

urls:
  html_extension_style: indexify

ui:
  bundle:
    url: https://xtdb-core2-ui-bundle.s3.eu-west-1.amazonaws.com/xtdb-core2docs-ui-v2-bundle.zip
    snapshot: true

asciidoc:
  attributes:
    page-pagination: true
  extensions:
    - ./antora-extensions/code-tabs.js
    - ./antora-extensions/railroads.js
