name: Auto Close Issues

on:
  pull_request:
    types: [closed]
jobs:
  close:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-close-fixed-issues@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # optional comment
          # comment: 'This issue was closed by #{{ pr }}.'
          # default ignore the pr merge to the default branch
          # ignore: true
