name: XTDB Kafka Connect
run-name: XTDB Kafka Connect

on:
  push:
    branches:
      - kafka-connect-latest

jobs:
  build-connector:
    name: Build and Upload XTDB Kafka Connector
    runs-on: ubuntu-latest
    if: github.repository == 'xtdb/xtdb'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1

      - name: Build Uberjar
        run: ./gradlew :modules:xtdb-kafka-connect:shadowJar
      - name: Upload Uberjar
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: xtdb-kafka-connector
          path: modules/kafka-connect/build/libs/xtdb-kafka-connect.jar
