name: XTDB CI
run-name: XTDB CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: test
          cache-read-only: ${{ github.ref != 'refs/heads/2.x' }}
      - name: Upload build reports
        if: success() || failure() # i.e. not cancelled
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/
      - name: Upload build reports (Core)
        if: success() || failure() # i.e. not cancelled
        uses: actions/upload-artifact@v3
        with:
          name: core-build-reports
          path: core/build/reports/
      - name: Post Slack Notification (On Fail)
        if: failure() && github.repository == 'xtdb/xtdb' && github.ref == 'refs/heads/2.x'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "*{workflow}* has {status_message}:"
          message_format: "{emoji} `test` job has {status_message} in *{workflow}*"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Integration Test
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: integration-test
          cache-read-only: ${{ github.ref != 'refs/heads/2.x' }}
      - name: Upload build reports
        if: success() || failure() # i.e. not cancelled
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/
      - name: Post Slack Notification (On Fail)
        if: failure() && github.repository == 'xtdb/xtdb' && github.ref == 'refs/heads/2.x'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "*{workflow}* has {status_message}:"
          message_format: "{emoji} `integration-test` job has {status_message} in *{workflow}*"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  slt-1:
    name: SLT 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: SLT 1
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: slt-test
          cache-read-only: ${{ github.ref != 'refs/heads/2.x' }}

  slt-2:
    name: SLT 2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: SLT 2
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: slt-test-2
          cache-read-only: ${{ github.ref != 'refs/heads/2.x' }}

  deploy-docker:
    name: Deploy XTDB Docker Image
    runs-on: ubuntu-latest
    if: github.repository == 'xtdb/xtdb' && github.ref == 'refs/heads/docker-latest'
    permissions:
      contents: read
      packages: write
    needs:
      - test
      - integration-test
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Uberjar
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: :docker:shadowJar
          cache-read-only: ${{ github.ref != 'refs/heads/2.x' }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker
          platforms: linux/arm/v7,linux/arm64/v8,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/xtdb/xtdb-standalone-ea:latest
          build-args: |
            GIT_SHA=${{ github.sha }}
            XTDB_VERSION="dev-SNAPSHOT"
