name: XTDB Kafka Connect
run-name: XTDB Kafka Connect

on:
  push:
    branches:
      - kafka-connect-latest

jobs:
  build-connector:
    name: Build and Upload XTDB Kafka Connector
    runs-on: ubuntu-latest
    if: github.repository == 'xtdb/xtdb'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
      - name: Set up JDK 21
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Build Uberjar
        run: ./gradlew :modules:xtdb-kafka-connect:shadowJar
      - name: Upload Uberjar
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: xtdb-kafka-connector
          path: modules/kafka-connect/build/libs/xtdb-kafka-connect.jar
