name: XTDB CI
run-name: XTDB CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: test
          cache-read-only: ${{ github.ref != 'refs/heads/2.x' }}
      - name: Upload build reports
        if: success() || failure() # i.e. not cancelled
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/

  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Integration Test
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: integration-test
          cache-read-only: ${{ github.ref != 'refs/heads/2.x' }}
      - name: Upload build reports
        if: success() || failure() # i.e. not cancelled
        uses: actions/upload-artifact@v3
        with:
          name: build-reports
          path: build/reports/

  slt-1:
    name: SLT 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: SLT 1
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: slt-test
          cache-read-only: ${{ github.ref != 'refs/heads/2.x' }}

  slt-2:
    name: SLT 2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: SLT 2
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: slt-test-2
          cache-read-only: ${{ github.ref != 'refs/heads/2.x' }}
