name: Docker images

on:
  workflow_call:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Log in to the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Standalone meta
        id: standalone-meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ghcr.io/xtdb/xtdb
          tags: &tags |
            type=semver,pattern={{version}}
            type=schedule
            type=schedule,pattern=nightly-{{date 'YYYYMMDD'}}
            type=edge,branch=main
            type=sha,prefix=g
          bake-target: standalone

      - name: AWS meta
        id: aws-meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ghcr.io/xtdb/xtdb-aws
          tags: *tags
          bake-target: aws

      - name: Azure meta
        id: azure-meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ghcr.io/xtdb/xtdb-azure
          tags: *tags
          bake-target: azure

      - name: Google Cloud meta
        id: google-cloud-meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ghcr.io/xtdb/xtdb-google-cloud
          tags: *tags
          bake-target: google-cloud

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5.0.1

      - name: Build Uberjars
        run: ./gradlew :docker:standalone:shadowJar :docker:aws:shadowJar :docker:azure:shadowJar :docker:google-cloud:shadowJar

      - name: Build and push
        uses: docker/bake-action@4ba453fbc2db7735392b93edf935aaf9b1e8eefc # v6.5.0
        with:
          files: |
            docker-bake.hcl
            ${{ steps.standalone-meta.outputs.bake-file }}
            ${{ steps.aws-meta.outputs.bake-file }}
            ${{ steps.azure-meta.outputs.bake-file }}
            ${{ steps.google-cloud-meta.outputs.bake-file }}
          targets: default
          push: ${{ github.event_name != 'pull_request' }}
          set: |
            *.args.GIT_SHA=${{ github.sha }}
            *.args.XTDB_VERSION=${{ steps.standalone-meta.outputs.version }}
