name: Docker images

on:
  workflow_call:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
      - name: Set up JDK 21
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Log in to the Container registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Standalone meta
        id: standalone-meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ghcr.io/xtdb/xtdb
          tags: |
            type=semver,pattern={{version}}
            type=schedule
            type=schedule,pattern=nightly-{{date 'YYYYMMDD'}}
            type=edge,branch=main
            type=sha,prefix=g

      - name: AWS meta
        id: aws-meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ghcr.io/xtdb/xtdb-aws
          tags: |
            type=semver,pattern={{version}}
            type=schedule
            type=schedule,pattern=nightly-{{date 'YYYYMMDD'}}
            type=edge,branch=main
            type=sha,prefix=g

      - name: Azure meta
        id: azure-meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ghcr.io/xtdb/xtdb-azure
          tags: |
            type=semver,pattern={{version}}
            type=schedule
            type=schedule,pattern=nightly-{{date 'YYYYMMDD'}}
            type=edge,branch=main
            type=sha,prefix=g

      - name: Google Cloud meta
        id: google-cloud-meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ghcr.io/xtdb/xtdb-google-cloud
          tags: |
            type=semver,pattern={{version}}
            type=schedule
            type=schedule,pattern=nightly-{{date 'YYYYMMDD'}}
            type=edge,branch=main
            type=sha,prefix=g

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Build Uberjar
        run: ./gradlew :docker:standalone:shadowJar :docker:aws:shadowJar :docker:azure:shadowJar :docker:google-cloud:shadowJar

      - name: Push Standalone
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: docker/standalone
          platforms: linux/arm64/v8,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.standalone-meta.outputs.tags }}
          labels: ${{ steps.standalone-meta.outputs.labels }}
          build-args: |
            GIT_SHA=${{ github.sha }}
            XTDB_VERSION=${{ steps.standalone-meta.outputs.version }}

      - name: Push Azure
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: docker/azure
          platforms: linux/arm64/v8,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.azure-meta.outputs.tags }}
          labels: ${{ steps.azure-meta.outputs.labels }}
          build-args: |
            GIT_SHA=${{ github.sha }}
            XTDB_VERSION=${{ steps.azure-meta.outputs.version }}

      - name: Push AWS
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: docker/aws
          platforms: linux/arm64/v8,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.aws-meta.outputs.tags }}
          labels: ${{ steps.aws-meta.outputs.labels }}
          build-args: |
            GIT_SHA=${{ github.sha }}
            XTDB_VERSION=${{ steps.aws-meta.outputs.version }}

      - name: Push Google Cloud
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: docker/google-cloud
          platforms: linux/arm64/v8,linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.google-cloud-meta.outputs.tags }}
          labels: ${{ steps.google-cloud-meta.outputs.labels }}
          build-args: |
            GIT_SHA=${{ github.sha }}
            XTDB_VERSION=${{ steps.google-cloud-meta.outputs.version }}
