name: Helm Charts

on:
  workflow_call:
    inputs:
      appVersion:
        required: true
        type: string

jobs:
  build-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      APP_VERSION: ${{ inputs.appVersion }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5

      - name: Setup Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4

      - name: Log in to the Container registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package & Push Azure Helm Chart
        run: |
          helm package azure/helm --app-version $APP_VERSION \
          ${{ env.APP_VERSION == 'edge' && '--version 2.0.0-SNAPSHOT' || '' }}
          helm push helm-xtdb-azure-*.tgz oci://ghcr.io/xtdb/

      - name: Package & Push Google Cloud Helm Chart
        run: |
          helm package google-cloud/helm --app-version $APP_VERSION \
          ${{ env.APP_VERSION == 'edge' && '--version 2.0.0-SNAPSHOT' || '' }}
          helm push helm-xtdb-google-cloud-*.tgz oci://ghcr.io/xtdb/

      - name: Package & Push AWS Helm Chart
        run: |
          helm package aws/helm --app-version $APP_VERSION \
          ${{ env.APP_VERSION == 'edge' && '--version 2.0.0-SNAPSHOT' || '' }}
          helm push helm-xtdb-aws-*.tgz oci://ghcr.io/xtdb/
