name: XTDB nightly tests

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 19 * * 1-5'

jobs:
  nightly-test:
    if: github.event_name == 'workflow_dispatch' || github.repository == 'xtdb/xtdb'
    name: Nightly test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    services:
      kafka:
        image: 'confluentinc/cp-kafka:7.5.1'
        ports:
          - '9092:9092'
        env:
          KAFKA_NODE_ID: 1
          KAFKA_ENABLE_KRAFT: yes
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
          KAFKA_BROKER_ID: 1
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
          ALLOW_PLAINTEXT_LISTENER: yes
          CLUSTER_ID: q1Sh-9_ISia_zwGINzRvyQ
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - id: 'google-cloud-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}'
      - name: Run Nightly Test Task
        uses: gradle/gradle-build-action@v2.6.1
        with:
          arguments: nightly-test
          cache-read-only: ${{ github.ref != 'refs/heads/2.x' }}
      - name: Publish Nightly Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          check_name: JUnit Nightly Test Report
          report_paths: '**/build/test-results/nightly-test/TEST-*.xml'
      - name: Post Slack Notification
        if: github.event_name != 'workflow_dispatch' && github.repository == 'xtdb/xtdb'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "*Nightly test*"
          message_format: "{emoji} *Nightly test* has {status_message}!"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
