name: XTDB Property Tests

on:
  workflow_call:
    inputs:
      iteration_count:
        description: 'Number of property test iterations to run'
        required: true
        type: string

jobs:
  property-test:
    name: Property Test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - name: Set up JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ed408507eac070d1f99cc633dbcf757c94c7933a # v4

      - name: Property Test
        run: ./gradlew property-test -Piterations=${{ inputs.iteration_count }}

      - name: Publish Property Test Report
        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3 # v5.6.2
        if: always()
        with:
          check_name: JUnit Property Test Report
          report_paths: '**/build/test-results/property-test/TEST-*.xml'

      - name: Post Slack Notification (On Fail)
        if: failure() && github.repository == 'xtdb/xtdb' && github.ref == 'refs/heads/main'
        uses: ravsamhq/notify-slack-action@042f29088bb3bdbda5b4ff7b4818466a277fa8f7 # v2
        with:
          status: ${{ job.status }}
          notification_title: "*Property Test* has {status_message}:"
          message_format: "{emoji} `property-test` job has {status_message} with ${{ inputs.iteration_count }} iterations"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
