name: XTDB Property Tests

on:
  workflow_call:
    inputs:
      iteration_count:
        description: 'Number of property test iterations to run'
        required: true
        type: string
      simulation_iteration_count:
        description: 'Number of simulation test iterations to run'
        required: true
        type: string

jobs:
  property-test:
    name: Property Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5
      - name: Set up JDK 21
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Property Test
        run: ./gradlew property-test -Piterations=${{ inputs.iteration_count }} -PsimulationIterations=${{ inputs.simulation_iteration_count }}

      - name: Publish Property Test Report
        uses: mikepenz/action-junit-report@e08919a3b1fb83a78393dfb775a9c37f17d8eea6 # v6.0.1
        if: always()
        with:
          check_name: JUnit Property Test Report
          report_paths: '**/build/test-results/property-test/TEST-*.xml'

      - name: Post Slack Notification (On Fail/Cancel)
        if: (failure() || cancelled()) && github.repository == 'xtdb/xtdb' && github.ref == 'refs/heads/main'
        uses: ravsamhq/notify-slack-action@be814b201e233b2dc673608aa46e5447c8ab13f2 # v2
        with:
          status: ${{ job.status }}
          notification_title: "*Property Test* has {status_message}:"
          message_format: "{emoji} `property-test` job has {status_message} with ${{ inputs.iteration_count }} iterations (${{ inputs.simulation_iteration_count }} simulation iterations)"
          notify_when: "failure,cancelled"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
