name: XTDB SLT
run-name: XTDB SLT

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 19 * * 1-5'

jobs:
  slt-test-dir:
    if: github.event_name == 'workflow_dispatch' || github.repository == 'xtdb/xtdb'
    name: SLT Test Dir
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        slt-dir: [{dir: "random/expr/", error: 62},
                  {dir: "random/aggregates/", error: 13, failure: 35},
                  {dir: "random/groupby/", error: 111},
                  {dir: "random/select/"},
                  {dir: "index/between/", error: 10},
                  {dir: "index/commute/", error: 10},
                  {dir: "index/orderby/", error: 60},
                  {dir: "index/orderby_nosort/"},
                  {dir: "index/in/"},
                  {dir: "index/random/", failure: 5}]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v3
      - name: Set up JDK 21
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: SLT Test Dir
        uses: gradle/gradle-build-action@915a66c096a03101667f9df2e56c9efef558b165 # v2.6.1
        with:
          arguments: slt-test-dir -PtestDir=${{ matrix.slt-dir.dir }} -PtestMaxErrors=${{ matrix.slt-dir.error }} -PtestMaxFailures=${{ matrix.slt-dir.failure }}
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Post Slack Notification
        if: failure()
        uses: ravsamhq/notify-slack-action@042f29088bb3bdbda5b4ff7b4818466a277fa8f7 # v2
        with:
          status: ${{ job.status }}
          notification_title: "*SLT Test*"
          message_format: "{emoji} Scheduled *SLT Test* has {status_message}!"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
