name: XTDB SLT
run-name: XTDB SLT

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 19 * * 1-5'

jobs:
  slt-test-dir:
    if: github.event_name == 'workflow_dispatch' || github.repository == 'xtdb/xtdb'
    name: SLT Test Dir
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        slt-dir: [{dir: "random/expr/", error: 62},
                  {dir: "random/aggregates/", error: 13, failure: 35},
                  {dir: "random/groupby/", error: 111},
                  {dir: "random/select/"},
                  {dir: "index/between/", error: 10},
                  {dir: "index/commute/", error: 10},
                  {dir: "index/orderby/", error: 60},
                  {dir: "index/orderby_nosort/"},
                  {dir: "index/in/"},
                  {dir: "index/random/", failure: 5}]
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v3
      - name: Set up JDK 21
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: SLT Test Dir
        uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
        with:
          arguments: slt-test-dir -PtestDir=${{ matrix.slt-dir.dir }} -PtestMaxErrors=${{ matrix.slt-dir.error }} -PtestMaxFailures=${{ matrix.slt-dir.failure }}
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: Post Slack Notification
        if: failure()
        uses: ravsamhq/notify-slack-action@be814b201e233b2dc673608aa46e5447c8ab13f2 # v2
        with:
          status: ${{ job.status }}
          notification_title: "*SLT Test*"
          message_format: "{emoji} Scheduled *SLT Test* has {status_message}!"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
