name: Trivy Security Scan

on:
  workflow_dispatch:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v5

      - name: Run Trivy against sample XTDBk8s
        uses: aquasecurity/trivy-action@c1824fd6edce30d7ab345a9989de00bbd46ef284 # v0.34.0
        with:
          scan-type: "fs"
          scan-ref: ./modules/azure/docs/azure-setup-guide/kubernetes/xtdb.yaml
          scanners: "vuln,secret,misconfig"
          format: 'template'
          output: 'trivy-report.html'
          template: '@.github/trivy/trivy-html-template.tpl'

      - name: HTML Trivy Report
        shell: bash
        if: always()
        run: 'cat $TRIVY_OUTPUT >> $GITHUB_STEP_SUMMARY'
